/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.dialogos;

/**
 *
 * @author David
 */
public class DialogoErrorValidacion extends javax.swing.JFrame {

    /**
     * Creates new form DialogoErrorValidacion
     */
    //int num;
    
    public DialogoErrorValidacion(int num) {
        //this.num = num;
        initComponents();
        textoDireccion(num);
        
    }
    
    
    
    public static void errorRazonSocial(){
        DialogoErrorValidacion direccion = new DialogoErrorValidacion(0);
        direccion.setVisible(true);
    }
    
    public static void errorDireccion(){
        DialogoErrorValidacion direccion = new DialogoErrorValidacion(1);
        
        direccion.setVisible(true);
    }
    
    public static void errorTelefono(){
        DialogoErrorValidacion direccion = new DialogoErrorValidacion(2);
        direccion.setVisible(true);
    }
    
    
    
    public void textoDireccion(int num){
        switch (num){
            case 0 :
                jTextArea1.setText("El campo  Razon Social ya existe,\n\nno se puede volver a usar\n\ny no puede estar vacio");
                break;
            case 1 :
                jTextArea1.setText("El campo  Direccion no se puede volver a usar,\n\no no puede quedarse vacio\n\nCompruebe los detalles");
                break;
            case 2 :
                jTextArea1.setText("El campo  Telefono debe rener el formato numerico de 9 digitos,\n\nOpcionalmente puede empezar por + prefijo internacional\n\nPrefijo de 1 o dos digitos. Por ejemplo +34 568798774");
                break;
            default :
                jTextArea1.setText("El campo  ya existe,\n\no esta mal\n\no esta vacio");
                
        }
          

    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabelErrorTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelErrorTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelErrorTitulo.setText("Error de validacion ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("El campo  Razon Social ya existe,\n\nno se puede volver a usar\n\ny no puede estar vacio");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelErrorTitulo)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabelErrorTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
