/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.vistas;

import java.io.IOException;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import mvc.controlador.ControladorEmpresa;
import mvc.controlador.ControladorTrabajador;
import mvc.dialogos.DialogoAcercaDe;

/**
 *
 * @author David
 */
public class VentanaEmpresaSubsidiaria extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEmpresaSubsidiaria
     */
    public VentanaEmpresaSubsidiaria() {
        initComponents();
        initDatos();
    }
    
    public void initDatos(){
        
        jButtonBorrar.setEnabled(false);
        jButtonModificar.setEnabled(false);
        
        jTextFieldRazonSocial.setEditable(true);
           jTextFieldDireccion.setEditable(true);
           jTextFieldTelefono.setEditable(true);
           jTextFieldCapitalSocial.setEditable(true);
           jTextFieldGananciasTotales.setEditable(true);
           
         if (ControladorEmpresa.getDatosEmpresa().isPresent()){
            jTextFieldRazonSocial.setText(ControladorEmpresa.getDatosEmpresa().get().getRazonSocial());
            jTextFieldDireccion.setText(ControladorEmpresa.getDatosEmpresa().get().getDireccion());
            jTextFieldTelefono.setText(ControladorEmpresa.getDatosEmpresa().get().getTelefono());
            jTextFieldCapitalSocial.setText(String.valueOf(ControladorEmpresa.getDatosEmpresa().get().getCapitalSocial()));
            jTextFieldGananciasTotales.setText(String.valueOf(ControladorEmpresa.getDatosEmpresa().get().getGananciasBruto()));
            
            jLabelTituloSub.setText("Empresa: " + ControladorEmpresa.getDatosEmpresa().get().getRazonSocial());
            
            DefaultListModel<String> subsidiarias = new DefaultListModel<String>();
            subsidiarias.addAll(ControladorEmpresa.listaTrabajadores(ControladorEmpresa.getDatosEmpresa().get()));
            jListTrabajadores.setModel(subsidiarias);
         }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanePrincipal = new javax.swing.JScrollPane();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelDatosEmpresa = new javax.swing.JPanel();
        jLabelDatosSubsidiaria = new javax.swing.JLabel();
        jLabelRazonSocial = new javax.swing.JLabel();
        jTextFieldRazonSocial = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelCapitalSocial = new javax.swing.JLabel();
        jLabelGananciasTotales = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldCapitalSocial = new javax.swing.JTextField();
        jTextFieldGananciasTotales = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPanelTrabajadores = new javax.swing.JPanel();
        jLabelTrabajadores = new javax.swing.JLabel();
        jScrollPaneTrabajadores = new javax.swing.JScrollPane();
        jListTrabajadores = new javax.swing.JList<>();
        jButtonModificar = new javax.swing.JButton();
        jButtonAnadir = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonIrATrabajadores = new javax.swing.JButton();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTituloSub = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevaEmpSub = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemRedo = new javax.swing.JMenuItem();
        jMenuItemUndo = new javax.swing.JMenuItem();
        jMenuInformes = new javax.swing.JMenu();
        jMenuItemInformeTrabajadores = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(204, 255, 204));

        jPanelDatosEmpresa.setBackground(new java.awt.Color(102, 153, 255));

        jLabelDatosSubsidiaria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDatosSubsidiaria.setText("Datos Subsidiaria");

        jLabelRazonSocial.setText("RazonSocial");

        jLabelDireccion.setText("Direccion");

        jLabelTelefono.setText("Telefono");

        jLabelCapitalSocial.setText("Capital Social");

        jLabelGananciasTotales.setText("Ganancias Totales");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosEmpresaLayout = new javax.swing.GroupLayout(jPanelDatosEmpresa);
        jPanelDatosEmpresa.setLayout(jPanelDatosEmpresaLayout);
        jPanelDatosEmpresaLayout.setHorizontalGroup(
            jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGananciasTotales)
                            .addComponent(jLabelCapitalSocial)
                            .addComponent(jLabelTelefono)
                            .addComponent(jLabelDireccion)
                            .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                                .addComponent(jLabelRazonSocial)
                                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabelDatosSubsidiaria))
                                    .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldDireccion)
                                            .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                                                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButtonGuardar)
                                                        .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(jTextFieldGananciasTotales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                                            .addComponent(jTextFieldCapitalSocial, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.Alignment.LEADING))))
                                                .addGap(0, 109, Short.MAX_VALUE))))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosEmpresaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)))
                .addContainerGap())
        );
        jPanelDatosEmpresaLayout.setVerticalGroup(
            jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDatosSubsidiaria)
                .addGap(37, 37, 37)
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRazonSocial)
                    .addComponent(jTextFieldRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccion)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCapitalSocial)
                    .addComponent(jTextFieldCapitalSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGananciasTotales)
                    .addComponent(jTextFieldGananciasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTrabajadores.setBackground(new java.awt.Color(102, 153, 255));

        jLabelTrabajadores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrabajadores.setText("Trabajadores");

        jListTrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTrabajadoresMouseClicked(evt);
            }
        });
        jScrollPaneTrabajadores.setViewportView(jListTrabajadores);

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonAnadir.setText("Añadir");
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");

        jButtonIrATrabajadores.setText("ir a trabajadores");
        jButtonIrATrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrATrabajadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTrabajadoresLayout = new javax.swing.GroupLayout(jPanelTrabajadores);
        jPanelTrabajadores.setLayout(jPanelTrabajadoresLayout);
        jPanelTrabajadoresLayout.setHorizontalGroup(
            jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrabajadoresLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabelTrabajadores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrabajadoresLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneTrabajadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrabajadoresLayout.createSequentialGroup()
                        .addGroup(jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonIrATrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(45, 45, 45))
        );
        jPanelTrabajadoresLayout.setVerticalGroup(
            jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrabajadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTrabajadores)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonAnadir))
                .addGap(32, 32, 32)
                .addGroup(jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonIrATrabajadores))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanelTitulo.setBackground(new java.awt.Color(204, 204, 255));

        jLabelTituloSub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabelTituloSub, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelTituloSub, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanelDatosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jPanelTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        jScrollPanePrincipal.setViewportView(jPanelPrincipal);

        jMenuArchivo.setText("Archivo");

        jMenuItemNuevaEmpSub.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemNuevaEmpSub.setText("Nueva Subsidiaria");
        jMenuArchivo.add(jMenuItemNuevaEmpSub);

        jMenuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemGuardar.setText("Guardar");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuardar);
        jMenuArchivo.add(jSeparator1);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuEditar.setText("Editar");

        jMenuItemRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemRedo.setText("Redo");
        jMenuEditar.add(jMenuItemRedo);

        jMenuItemUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemUndo.setText("Undo");
        jMenuEditar.add(jMenuItemUndo);

        jMenuBar1.add(jMenuEditar);

        jMenuInformes.setText("Informes");

        jMenuItemInformeTrabajadores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemInformeTrabajadores.setText("Informe Trabajadores");
        jMenuItemInformeTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInformeTrabajadoresActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemInformeTrabajadores);

        jMenuBar1.add(jMenuInformes);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAcerca.setText("Acerca");
        jMenuItemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcerca);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jListTrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTrabajadoresMouseClicked
        // TODO add your handling code here:
        
        jButtonBorrar.setEnabled(true);
        jButtonModificar.setEnabled(true);
    }//GEN-LAST:event_jListTrabajadoresMouseClicked

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
        // TODO add your handling code here:
        ControladorTrabajador.initTrabajador(Optional.empty());
        
    }//GEN-LAST:event_jButtonAnadirActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        ControladorEmpresa.guardarSubsidiaria(jTextFieldRazonSocial.getText(), jTextFieldDireccion.getText(), jTextFieldTelefono.getText(), Double.parseDouble(jTextFieldCapitalSocial.getText()), Double.parseDouble(jTextFieldGananciasTotales.getText()));
        
        dispose();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        // TODO add your handling code here:
        ControladorEmpresa.guardarSubsidiaria(jTextFieldRazonSocial.getText(), jTextFieldDireccion.getText(), jTextFieldTelefono.getText(), Double.parseDouble(jTextFieldCapitalSocial.getText()), Double.parseDouble(jTextFieldGananciasTotales.getText()));
        dispose();
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        ControladorTrabajador.initTrabajador(Optional.of(ControladorEmpresa.modificarTrabajador(jListTrabajadores.getSelectedValue())));
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jMenuItemInformeTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInformeTrabajadoresActionPerformed
        try {
            // TODO add your handling code here:
            ControladorEmpresa.agrirInformeTrabajadoresSubsidiaria();
        } catch (IOException ex) {
            Logger.getLogger(VentanaEmpresaSubsidiaria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemInformeTrabajadoresActionPerformed

    private void jButtonIrATrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrATrabajadoresActionPerformed
        // TODO add your handling code here:
        ControladorTrabajador.initTrabajadores(ControladorEmpresa.getDatosEmpresa());
    }//GEN-LAST:event_jButtonIrATrabajadoresActionPerformed

    private void jMenuItemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaActionPerformed
        // TODO add your handling code here:
        DialogoAcercaDe.acercaDe();
    }//GEN-LAST:event_jMenuItemAcercaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadir;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonIrATrabajadores;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabelCapitalSocial;
    private javax.swing.JLabel jLabelDatosSubsidiaria;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelGananciasTotales;
    private javax.swing.JLabel jLabelRazonSocial;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTituloSub;
    private javax.swing.JLabel jLabelTrabajadores;
    private javax.swing.JList<String> jListTrabajadores;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuInformes;
    private javax.swing.JMenuItem jMenuItemAcerca;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemInformeTrabajadores;
    private javax.swing.JMenuItem jMenuItemNuevaEmpSub;
    private javax.swing.JMenuItem jMenuItemRedo;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemUndo;
    private javax.swing.JPanel jPanelDatosEmpresa;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelTrabajadores;
    private javax.swing.JScrollPane jScrollPanePrincipal;
    private javax.swing.JScrollPane jScrollPaneTrabajadores;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextFieldCapitalSocial;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldGananciasTotales;
    private javax.swing.JTextField jTextFieldRazonSocial;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
