/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.vistas;

//import informes.GeneraInformes;
//import java.io.IOException;
import java.util.stream.Collectors;
//import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import modelo.empresas.Empresa;
import mvc.controlador.ControladorEmpresa;
//import javax.swing.DefaultListModel;
//import modelo.empresas.Empresa;
import mvc.controlador.ControladorPrincipal;
import mvc.dialogos.DialogoAcercaDe;

/**
 *
 * @author David
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    
    
    public VentanaPrincipal() {
        initComponents();
        initDatos();
    }
    
    private void initDatos(){
        initComboBox();
    }
    
    public void initComboBox(){
        
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<String>();
        modelo.addAll(ControladorPrincipal.getListaEmpresa().stream().map(e -> e.getRazonSocial()).collect(Collectors.toList()));
        jComboBoxEmpresas.setModel( modelo);

            
            btnAnadir.setEnabled(true);
            btnBorrar.setEnabled(false);
            btnModificar.setEnabled(false);
            
         jTextAreaInfoEmpresa.setEditable(false);

    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanePrincipal = new javax.swing.JScrollPane();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabelInfoResumen = new javax.swing.JLabel();
        jScrollPaneTextArea = new javax.swing.JScrollPane();
        jTextAreaInfoEmpresa = new javax.swing.JTextArea();
        jPanelBotonesCombo = new javax.swing.JPanel();
        btnAnadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jComboBoxEmpresas = new javax.swing.JComboBox<>();
        jLabelElije = new javax.swing.JLabel();
        jLabelTituloAplicacion = new javax.swing.JLabel();
        jMenuBarVentanaPrincipal = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevaEmpresa = new javax.swing.JMenuItem();
        jMenuItemModificar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemRedo = new javax.swing.JMenuItem();
        jMenuItemUndo = new javax.swing.JMenuItem();
        jMenuInformes = new javax.swing.JMenu();
        jMenuItemInformeEmpresas = new javax.swing.JMenuItem();
        jMenuAcerca = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(204, 255, 204));

        jLabelInfoResumen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInfoResumen.setText("Informacion Resumen de la empresa");

        jTextAreaInfoEmpresa.setColumns(20);
        jTextAreaInfoEmpresa.setRows(5);
        jScrollPaneTextArea.setViewportView(jTextAreaInfoEmpresa);

        jPanelBotonesCombo.setBackground(new java.awt.Color(102, 153, 255));

        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jComboBoxEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpresasActionPerformed(evt);
            }
        });

        jLabelElije.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelElije.setText("Elija la empresa con la que quiere trabajar");

        javax.swing.GroupLayout jPanelBotonesComboLayout = new javax.swing.GroupLayout(jPanelBotonesCombo);
        jPanelBotonesCombo.setLayout(jPanelBotonesComboLayout);
        jPanelBotonesComboLayout.setHorizontalGroup(
            jPanelBotonesComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesComboLayout.createSequentialGroup()
                .addGroup(jPanelBotonesComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotonesComboLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnadir)
                        .addGap(18, 18, 18))
                    .addGroup(jPanelBotonesComboLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabelElije, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)))
                .addGroup(jPanelBotonesComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxEmpresas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBotonesComboLayout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar)))
                .addGap(72, 72, 72))
        );
        jPanelBotonesComboLayout.setVerticalGroup(
            jPanelBotonesComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesComboLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanelBotonesComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxEmpresas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelElije, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39)
                .addGroup(jPanelBotonesComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnadir)
                    .addComponent(btnModificar)
                    .addComponent(btnBorrar))
                .addGap(43, 43, 43))
        );

        jLabelTituloAplicacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTituloAplicacion.setText("Aplicacion Trabajadores Empresas");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(491, 491, 491)
                        .addComponent(jLabelInfoResumen))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneTextArea)
                            .addComponent(jPanelBotonesCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(jLabelTituloAplicacion)))
                .addContainerGap(426, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabelTituloAplicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jPanelBotonesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabelInfoResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPanePrincipal.setViewportView(jPanelPrincipal);

        jMenuArchivo.setText("Archivo");

        jMenuItemNuevaEmpresa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemNuevaEmpresa.setText("Nueva Empresa");
        jMenuItemNuevaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaEmpresaActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemNuevaEmpresa);

        jMenuItemModificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemModificar.setText("Modificar");
        jMenuItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemModificar);
        jMenuArchivo.add(jSeparator1);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        jMenuItemSalir.setText("Salir ");
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBarVentanaPrincipal.add(jMenuArchivo);

        jMenuEditar.setText("Editar");

        jMenuItemRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemRedo.setText("Redo");
        jMenuEditar.add(jMenuItemRedo);

        jMenuItemUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemUndo.setText("Undo");
        jMenuEditar.add(jMenuItemUndo);

        jMenuBarVentanaPrincipal.add(jMenuEditar);

        jMenuInformes.setText("Informes");

        jMenuItemInformeEmpresas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemInformeEmpresas.setText("Informe Empresas");
        jMenuItemInformeEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInformeEmpresasActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemInformeEmpresas);

        jMenuBarVentanaPrincipal.add(jMenuInformes);

        jMenuAcerca.setText("Ayuda");

        jMenuItemAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAcercaDe.setText("Acerca de");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuAcerca.add(jMenuItemAcercaDe);

        jMenuBarVentanaPrincipal.add(jMenuAcerca);

        setJMenuBar(jMenuBarVentanaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpresasActionPerformed
        // TODO add your handling code here:
        jTextAreaInfoEmpresa.setText("");
        
        btnAnadir.setEnabled(true);
        btnBorrar.setEnabled(true);
        btnModificar.setEnabled(true);
        
        jTextAreaInfoEmpresa.insert(ControladorPrincipal.infoEmpresa((String) jComboBoxEmpresas.getSelectedItem()), (int) CENTER_ALIGNMENT);

    }//GEN-LAST:event_jComboBoxEmpresasActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        // TODO add your handling code here:
        ControladorPrincipal.nuevo();
        
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void jMenuItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarActionPerformed
        // TODO add your handling code here:
        ControladorPrincipal.modificarEmpresa((String) jComboBoxEmpresas.getSelectedItem());
        
        
    }//GEN-LAST:event_jMenuItemModificarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        ControladorPrincipal.modificarEmpresa((String) jComboBoxEmpresas.getSelectedItem());
        ControladorEmpresa.getEmpresaMatriz((String) jComboBoxEmpresas.getSelectedItem());
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        ControladorPrincipal.borrarEmpresa((String) jComboBoxEmpresas.getSelectedItem());
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void jMenuItemInformeEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInformeEmpresasActionPerformed
        // TODO add your handling code here:
        
        ControladorPrincipal.abrirArchivo();
    }//GEN-LAST:event_jMenuItemInformeEmpresasActionPerformed

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        // TODO add your handling code here:
        DialogoAcercaDe.acercaDe();
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void jMenuItemNuevaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaEmpresaActionPerformed
        // TODO add your handling code here:
        ControladorPrincipal.nuevo();
    }//GEN-LAST:event_jMenuItemNuevaEmpresaActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> jComboBoxEmpresas;
    private javax.swing.JLabel jLabelElije;
    private javax.swing.JLabel jLabelInfoResumen;
    private javax.swing.JLabel jLabelTituloAplicacion;
    private javax.swing.JMenu jMenuAcerca;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBarVentanaPrincipal;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuInformes;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemInformeEmpresas;
    private javax.swing.JMenuItem jMenuItemModificar;
    private javax.swing.JMenuItem jMenuItemNuevaEmpresa;
    private javax.swing.JMenuItem jMenuItemRedo;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemUndo;
    private javax.swing.JPanel jPanelBotonesCombo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPanePrincipal;
    private javax.swing.JScrollPane jScrollPaneTextArea;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextAreaInfoEmpresa;
    // End of variables declaration//GEN-END:variables
}
